<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hacker theme</title>
</head>
<body>
    <h1>Hacker theme</h1>
    <p><strong>Description:</strong> Hacker is a theme for GitHub Pages.</p>
    <p><strong>Show Downloads:</strong> true</p>
    <p><strong>Google Analytics:</strong></p>
    <p><strong>Theme:</strong> jekyll-theme-hacker</p>

    <h2>Sass Configuration</h2>
    <ul>
        <li><strong>Style:</strong> compressed</li>
        <li><strong>Sass Directory:</strong> _sass</li>
        <li><strong>CSS Directory:</strong> assets/css</li>
    </ul>
</body>
</html>
